name: Deploy Fuyu RAG to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login en el almacén (ACR) usando los secretos de GitHub directamente
      - name: Log in to ACR
        run: |
          # Usamos el Client ID del Service Principal que ya tienes
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ca19777e4b99acr.azurecr.io -u 33befc6c-8a94-4fed-8ab3-976f25fc5868 --password-stdin

      - name: Build and push image
        run: |
          docker build . -t ca19777e4b99acr.azurecr.io/fuyu-tutor:latest
          docker push ca19777e4b99acr.azurecr.io/fuyu-tutor:latest

      - name: Deploy to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: fuyu-tutor-wladimir
          resourceGroup: rg-fuyu-mlops
          imageToDeploy: ca19777e4b99acr.azurecr.io/fuyu-tutor:latest
          registryUrl: ca19777e4b99acr.azurecr.io
          # Aquí mandamos las credenciales fijas para que la App no se pierda
          registryUsername: 33befc6c-8a94-4fed-8ab3-976f25fc5868
          registryPassword: ${{ secrets.ACR_PASSWORD }}
          targetPort: 8000
          ingress: external